/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactFormSubmission {
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface CustomMailTemplate {
  'id' : string,
  'subject' : string,
  'body' : string,
  'name' : string,
  'createdAt' : Time,
}
export interface JobApplication {
  'yearsOfExperience' : string,
  'appliedAt' : Time,
  'applicantName' : string,
  'jobId' : string,
  'resumeFileId' : string,
  'email' : string,
  'expectedCTC' : string,
  'currentCTC' : string,
}
export interface JobPosition {
  'id' : string,
  'title' : string,
  'salary' : bigint,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'department' : string,
  'location' : string,
}
export interface MailConfig {
  'contactTemplate' : MailTemplate,
  'roiTemplate' : MailTemplate,
}
export interface MailTemplate { 'subject' : string, 'body' : string }
export interface ROINewLead {
  'name' : string,
  'abandonedLeads' : string,
  'submittedAt' : Time,
  'email' : string,
  'staffHours' : string,
  'phone' : string,
  'calculatedGain' : string,
  'monthlyRevenue' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomMailTemplate' : ActorMethod<
    [CustomMailTemplate],
    CustomMailTemplate
  >,
  'createJobPosition' : ActorMethod<[JobPosition], JobPosition>,
  'deleteCustomMailTemplate' : ActorMethod<[bigint], undefined>,
  'deleteJobPosition' : ActorMethod<[bigint], undefined>,
  'getAllActiveJobPositions' : ActorMethod<[], Array<JobPosition>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getAllCustomMailTemplates' : ActorMethod<[], Array<CustomMailTemplate>>,
  'getAllJobApplications' : ActorMethod<[], Array<JobApplication>>,
  'getAllJobPositions' : ActorMethod<[], Array<JobPosition>>,
  'getAllROINewLeads' : ActorMethod<[], Array<ROINewLead>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobPosition' : ActorMethod<[bigint], [] | [JobPosition]>,
  'getMailConfig' : ActorMethod<[], [] | [MailConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMailConfig' : ActorMethod<[MailConfig], undefined>,
  'submitContactForm' : ActorMethod<[ContactFormSubmission], undefined>,
  'submitJobApplication' : ActorMethod<[JobApplication], undefined>,
  'submitROILead' : ActorMethod<[ROINewLead], undefined>,
  'updateCustomMailTemplate' : ActorMethod<
    [bigint, CustomMailTemplate],
    undefined
  >,
  'updateJobPosition' : ActorMethod<[bigint, JobPosition], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];