/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactFormSubmission {
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface CustomMailTemplate {
  'id' : string,
  'subject' : string,
  'body' : string,
  'name' : string,
  'createdAt' : Time,
}
export interface Employee {
  'dob' : string,
  'salary' : string,
  'role' : string,
  'dateOfJoining' : string,
  'employeeId' : string,
  'aadharNumber' : string,
  'address' : string,
  'panNumber' : string,
  'passwordHash' : string,
  'pincode' : string,
  'position' : string,
  'lastName' : string,
  'maritalStatus' : string,
  'firstName' : string,
  'email' : string,
  'mobile' : string,
  'city' : string,
  'state' : string,
  'profilePhotoFileId' : string,
}
export interface JobApplication {
  'yearsOfExperience' : string,
  'appliedAt' : Time,
  'applicantName' : string,
  'jobId' : string,
  'resumeFileId' : string,
  'email' : string,
  'expectedCTC' : string,
  'currentCTC' : string,
}
export interface JobPosition {
  'id' : string,
  'title' : string,
  'salary' : bigint,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'department' : string,
  'location' : string,
}
export interface MailConfig {
  'contactTemplate' : MailTemplate,
  'roiTemplate' : MailTemplate,
}
export interface MailTemplate { 'subject' : string, 'body' : string }
export interface ROINewLead {
  'name' : string,
  'abandonedLeads' : string,
  'submittedAt' : Time,
  'email' : string,
  'staffHours' : string,
  'phone' : string,
  'calculatedGain' : string,
  'monthlyRevenue' : string,
}
export interface Ticket {
  'status' : string,
  'createdAt' : Time,
  'description' : string,
  'ticketNumber' : string,
  'notes' : string,
  'category' : string,
  'raisedBy' : string,
  'resolvedAt' : [] | [Time],
}
export type Time = bigint;
export interface TimesheetEntry {
  'id' : string,
  'date' : string,
  'checkInTime' : [] | [Time],
  'employeeId' : string,
  'checkOutTime' : [] | [Time],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeEmployeePassword' : ActorMethod<[string, string, string], boolean>,
  'checkIn' : ActorMethod<[string, string], TimesheetEntry>,
  'checkOut' : ActorMethod<[string, string], [] | [TimesheetEntry]>,
  'createCustomMailTemplate' : ActorMethod<
    [CustomMailTemplate],
    CustomMailTemplate
  >,
  'createEmployee' : ActorMethod<[Employee], Employee>,
  'createJobPosition' : ActorMethod<[JobPosition], JobPosition>,
  'createTicket' : ActorMethod<[string, string, string], Ticket>,
  'deleteCustomMailTemplate' : ActorMethod<[bigint], undefined>,
  'deleteEmployee' : ActorMethod<[string], boolean>,
  'deleteJobPosition' : ActorMethod<[bigint], undefined>,
  'employeeLogin' : ActorMethod<[string, string], [] | [Employee]>,
  'getAdminPasswordHash' : ActorMethod<[], string>,
  'getAllActiveJobPositions' : ActorMethod<[], Array<JobPosition>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getAllCustomMailTemplates' : ActorMethod<[], Array<CustomMailTemplate>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllJobApplications' : ActorMethod<[], Array<JobApplication>>,
  'getAllJobPositions' : ActorMethod<[], Array<JobPosition>>,
  'getAllROINewLeads' : ActorMethod<[], Array<ROINewLead>>,
  'getAllTickets' : ActorMethod<[], Array<Ticket>>,
  'getAllTimesheets' : ActorMethod<[], Array<TimesheetEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[string], [] | [Employee]>,
  'getJobPosition' : ActorMethod<[bigint], [] | [JobPosition]>,
  'getMailConfig' : ActorMethod<[], [] | [MailConfig]>,
  'getTicketsByEmployee' : ActorMethod<[string], Array<Ticket>>,
  'getTimesheetByEmployee' : ActorMethod<[string], Array<TimesheetEntry>>,
  'getTodayTimesheetEntry' : ActorMethod<
    [string, string],
    [] | [TimesheetEntry]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminPasswordHash' : ActorMethod<[string], undefined>,
  'setMailConfig' : ActorMethod<[MailConfig], undefined>,
  'submitContactForm' : ActorMethod<[ContactFormSubmission], undefined>,
  'submitJobApplication' : ActorMethod<[JobApplication], undefined>,
  'submitROILead' : ActorMethod<[ROINewLead], undefined>,
  'updateCustomMailTemplate' : ActorMethod<
    [bigint, CustomMailTemplate],
    undefined
  >,
  'updateEmployee' : ActorMethod<[string, Employee], boolean>,
  'updateEmployeeProfilePhoto' : ActorMethod<[string, string], boolean>,
  'updateJobPosition' : ActorMethod<[bigint, JobPosition], undefined>,
  'updateTicketStatus' : ActorMethod<[string, string, string], boolean>,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
