/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomMailTemplate = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const JobPosition = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'salary' : IDL.Nat,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const JobApplication = IDL.Record({
  'yearsOfExperience' : IDL.Text,
  'appliedAt' : Time,
  'applicantName' : IDL.Text,
  'jobId' : IDL.Text,
  'resumeFileId' : IDL.Text,
  'email' : IDL.Text,
  'expectedCTC' : IDL.Text,
  'currentCTC' : IDL.Text,
});
export const ROINewLead = IDL.Record({
  'name' : IDL.Text,
  'abandonedLeads' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'staffHours' : IDL.Text,
  'phone' : IDL.Text,
  'calculatedGain' : IDL.Text,
  'monthlyRevenue' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MailTemplate = IDL.Record({
  'subject' : IDL.Text,
  'body' : IDL.Text,
});
export const MailConfig = IDL.Record({
  'contactTemplate' : MailTemplate,
  'roiTemplate' : MailTemplate,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomMailTemplate' : IDL.Func(
      [CustomMailTemplate],
      [CustomMailTemplate],
      [],
    ),
  'createJobPosition' : IDL.Func([JobPosition], [JobPosition], []),
  'deleteCustomMailTemplate' : IDL.Func([IDL.Nat], [], []),
  'deleteJobPosition' : IDL.Func([IDL.Nat], [], []),
  'getAllActiveJobPositions' : IDL.Func([], [IDL.Vec(JobPosition)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllCustomMailTemplates' : IDL.Func(
      [],
      [IDL.Vec(CustomMailTemplate)],
      ['query'],
    ),
  'getAllJobApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getAllJobPositions' : IDL.Func([], [IDL.Vec(JobPosition)], ['query']),
  'getAllROINewLeads' : IDL.Func([], [IDL.Vec(ROINewLead)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobPosition' : IDL.Func([IDL.Nat], [IDL.Opt(JobPosition)], ['query']),
  'getMailConfig' : IDL.Func([], [IDL.Opt(MailConfig)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMailConfig' : IDL.Func([MailConfig], [], []),
  'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
  'submitJobApplication' : IDL.Func([JobApplication], [], []),
  'submitROILead' : IDL.Func([ROINewLead], [], []),
  'updateCustomMailTemplate' : IDL.Func([IDL.Nat, CustomMailTemplate], [], []),
  'updateJobPosition' : IDL.Func([IDL.Nat, JobPosition], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomMailTemplate = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const JobPosition = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'salary' : IDL.Nat,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const JobApplication = IDL.Record({
    'yearsOfExperience' : IDL.Text,
    'appliedAt' : Time,
    'applicantName' : IDL.Text,
    'jobId' : IDL.Text,
    'resumeFileId' : IDL.Text,
    'email' : IDL.Text,
    'expectedCTC' : IDL.Text,
    'currentCTC' : IDL.Text,
  });
  const ROINewLead = IDL.Record({
    'name' : IDL.Text,
    'abandonedLeads' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'staffHours' : IDL.Text,
    'phone' : IDL.Text,
    'calculatedGain' : IDL.Text,
    'monthlyRevenue' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MailTemplate = IDL.Record({ 'subject' : IDL.Text, 'body' : IDL.Text });
  const MailConfig = IDL.Record({
    'contactTemplate' : MailTemplate,
    'roiTemplate' : MailTemplate,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomMailTemplate' : IDL.Func(
        [CustomMailTemplate],
        [CustomMailTemplate],
        [],
      ),
    'createJobPosition' : IDL.Func([JobPosition], [JobPosition], []),
    'deleteCustomMailTemplate' : IDL.Func([IDL.Nat], [], []),
    'deleteJobPosition' : IDL.Func([IDL.Nat], [], []),
    'getAllActiveJobPositions' : IDL.Func(
        [],
        [IDL.Vec(JobPosition)],
        ['query'],
      ),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllCustomMailTemplates' : IDL.Func(
        [],
        [IDL.Vec(CustomMailTemplate)],
        ['query'],
      ),
    'getAllJobApplications' : IDL.Func(
        [],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getAllJobPositions' : IDL.Func([], [IDL.Vec(JobPosition)], ['query']),
    'getAllROINewLeads' : IDL.Func([], [IDL.Vec(ROINewLead)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobPosition' : IDL.Func([IDL.Nat], [IDL.Opt(JobPosition)], ['query']),
    'getMailConfig' : IDL.Func([], [IDL.Opt(MailConfig)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMailConfig' : IDL.Func([MailConfig], [], []),
    'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
    'submitJobApplication' : IDL.Func([JobApplication], [], []),
    'submitROILead' : IDL.Func([ROINewLead], [], []),
    'updateCustomMailTemplate' : IDL.Func(
        [IDL.Nat, CustomMailTemplate],
        [],
        [],
      ),
    'updateJobPosition' : IDL.Func([IDL.Nat, JobPosition], [], []),
  });
};

export const init = ({ IDL }) => { return []; };