/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface CustomMailTemplate {
    id: string;
    subject: string;
    body: string;
    name: string;
    createdAt: Time;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TimesheetEntry {
    id: string;
    date: string;
    checkInTime?: Time;
    employeeId: string;
    checkOutTime?: Time;
}
export interface JobApplication {
    yearsOfExperience: string;
    appliedAt: Time;
    applicantName: string;
    jobId: string;
    resumeFileId: string;
    email: string;
    expectedCTC: string;
    currentCTC: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MailConfig {
    contactTemplate: MailTemplate;
    roiTemplate: MailTemplate;
}
export interface ContactFormSubmission {
    name: string;
    submittedAt: Time;
    email: string;
    message: string;
    phone: string;
}
export interface MailTemplate {
    subject: string;
    body: string;
}
export interface ROINewLead {
    name: string;
    abandonedLeads: string;
    submittedAt: Time;
    email: string;
    staffHours: string;
    phone: string;
    calculatedGain: string;
    monthlyRevenue: string;
}
export interface Employee {
    dob: string;
    salary: string;
    role: string;
    dateOfJoining: string;
    employeeId: string;
    aadharNumber: string;
    address: string;
    panNumber: string;
    passwordHash: string;
    pincode: string;
    position: string;
    lastName: string;
    maritalStatus: string;
    firstName: string;
    email: string;
    mobile: string;
    city: string;
    state: string;
}
export interface Ticket {
    status: string;
    createdAt: Time;
    description: string;
    ticketNumber: string;
    notes: string;
    category: string;
    raisedBy: string;
    resolvedAt?: Time;
}
export interface Announcement {
    id: string;
    title: string;
    content: string;
    mediaFileId: string;
    mediaType: string;
    createdAt: Time;
}
export interface UserProfile {
    name: string;
}
export interface JobPosition {
    id: string;
    title: string;
    salary: bigint;
    createdAt: Time;
    description: string;
    isActive: boolean;
    department: string;
    location: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface LeaveRequest {
    id: string;
    employeeId: string;
    reason: string;
    startDate: string;
    endDate: string;
    numberOfDays: bigint;
    status: string;
    requestedAt: Time;
    approvedAt?: Time;
}

export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changeEmployeePassword(employeeId: string, oldPassword: string, newPassword: string): Promise<boolean>;
    checkIn(employeeId: string, date: string): Promise<TimesheetEntry>;
    checkOut(employeeId: string, date: string): Promise<TimesheetEntry | null>;
    createCustomMailTemplate(input: CustomMailTemplate): Promise<CustomMailTemplate>;
    createEmployee(input: Employee): Promise<Employee>;
    createJobPosition(input: JobPosition): Promise<JobPosition>;
    createTicket(employeeId: string, category: string, description: string): Promise<Ticket>;
    createAnnouncement(title: string, content: string, mediaFileId: string, mediaType: string): Promise<Announcement>;
    deleteCustomMailTemplate(id: bigint): Promise<void>;
    deleteEmployee(id: string): Promise<boolean>;
    deleteAnnouncement(id: string): Promise<boolean>;
    deleteJobPosition(id: bigint): Promise<void>;
    employeeLogin(employeeId: string, password: string): Promise<Employee | null>;
    getAdminPasswordHash(): Promise<string>;
    getAllActiveJobPositions(): Promise<Array<JobPosition>>;
    getAllContactSubmissions(): Promise<Array<ContactFormSubmission>>;
    getAllCustomMailTemplates(): Promise<Array<CustomMailTemplate>>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAllJobApplications(): Promise<Array<JobApplication>>;
    getAllJobPositions(): Promise<Array<JobPosition>>;
    getAllROINewLeads(): Promise<Array<ROINewLead>>;
    getAllTickets(): Promise<Array<Ticket>>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllTimesheets(): Promise<Array<TimesheetEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmployee(id: string): Promise<Employee | null>;
    getJobPosition(id: bigint): Promise<JobPosition | null>;
    getMailConfig(): Promise<MailConfig | null>;
    getTicketsByEmployee(employeeId: string): Promise<Array<Ticket>>;
    getTimesheetByEmployee(employeeId: string): Promise<Array<TimesheetEntry>>;
    getTodayTimesheetEntry(employeeId: string, date: string): Promise<TimesheetEntry | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAdminPasswordHash(newHash: string): Promise<void>;
    setMailConfig(config: MailConfig): Promise<void>;
    submitContactForm(submission: ContactFormSubmission): Promise<void>;
    submitJobApplication(application: JobApplication): Promise<void>;
    submitROILead(roi: ROINewLead): Promise<void>;
    updateCustomMailTemplate(id: bigint, template: CustomMailTemplate): Promise<void>;
    updateEmployee(id: string, data: Employee): Promise<boolean>;
    updateJobPosition(id: bigint, position: JobPosition): Promise<void>;
    updateTicketStatus(ticketNumber: string, status: string, notes: string): Promise<boolean>;
    verifyAdminPassword(password: string): Promise<boolean>;
}
import type { Employee as _Employee, JobPosition as _JobPosition, MailConfig as _MailConfig, Ticket as _Ticket, Time as _Time, TimesheetEntry as _TimesheetEntry, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeEmployeePassword(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeEmployeePassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeEmployeePassword(arg0, arg1, arg2);
            return result;
        }
    }
    async checkIn(arg0: string, arg1: string): Promise<TimesheetEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIn(arg0, arg1);
                return from_candid_TimesheetEntry_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIn(arg0, arg1);
            return from_candid_TimesheetEntry_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkOut(arg0: string, arg1: string): Promise<TimesheetEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOut(arg0, arg1);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOut(arg0, arg1);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCustomMailTemplate(arg0: CustomMailTemplate): Promise<CustomMailTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomMailTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomMailTemplate(arg0);
            return result;
        }
    }
    async createEmployee(arg0: Employee): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(arg0);
            return result;
        }
    }
    async createJobPosition(arg0: JobPosition): Promise<JobPosition> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobPosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobPosition(arg0);
            return result;
        }
    }
    async createTicket(arg0: string, arg1: string, arg2: string): Promise<Ticket> {
        if (this.processError) {
            try {
                const result = await this.actor.createTicket(arg0, arg1, arg2);
                return from_candid_Ticket_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTicket(arg0, arg1, arg2);
            return from_candid_Ticket_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCustomMailTemplate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomMailTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomMailTemplate(arg0);
            return result;
        }
    }
    async deleteEmployee(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async deleteJobPosition(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobPosition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobPosition(arg0);
            return result;
        }
    }
    async employeeLogin(arg0: string, arg1: string): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.employeeLogin(arg0, arg1);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.employeeLogin(arg0, arg1);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPasswordHash(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPasswordHash();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPasswordHash();
            return result;
        }
    }
    async getAllActiveJobPositions(): Promise<Array<JobPosition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveJobPositions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveJobPositions();
            return result;
        }
    }
    async getAllContactSubmissions(): Promise<Array<ContactFormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactSubmissions();
            return result;
        }
    }
    async getAllCustomMailTemplates(): Promise<Array<CustomMailTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomMailTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomMailTemplates();
            return result;
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return result;
        }
    }
    async getAllJobApplications(): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobApplications();
            return result;
        }
    }
    async getAllJobPositions(): Promise<Array<JobPosition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobPositions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobPositions();
            return result;
        }
    }
    async getAllROINewLeads(): Promise<Array<ROINewLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllROINewLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllROINewLeads();
            return result;
        }
    }
    async getAllTickets(): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTickets();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTickets();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTimesheets(): Promise<Array<TimesheetEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTimesheets();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTimesheets();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: string): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobPosition(arg0: bigint): Promise<JobPosition | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobPosition(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobPosition(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMailConfig(): Promise<MailConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMailConfig();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMailConfig();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicketsByEmployee(arg0: string): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketsByEmployee(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketsByEmployee(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimesheetByEmployee(arg0: string): Promise<Array<TimesheetEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimesheetByEmployee(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimesheetByEmployee(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayTimesheetEntry(arg0: string, arg1: string): Promise<TimesheetEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayTimesheetEntry(arg0, arg1);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayTimesheetEntry(arg0, arg1);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAdminPasswordHash(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPasswordHash(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPasswordHash(arg0);
            return result;
        }
    }
    async setMailConfig(arg0: MailConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMailConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMailConfig(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: ContactFormSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0);
            return result;
        }
    }
    async submitJobApplication(arg0: JobApplication): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitJobApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitJobApplication(arg0);
            return result;
        }
    }
    async submitROILead(arg0: ROINewLead): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitROILead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitROILead(arg0);
            return result;
        }
    }
    async updateCustomMailTemplate(arg0: bigint, arg1: CustomMailTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomMailTemplate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomMailTemplate(arg0, arg1);
            return result;
        }
    }
    async updateEmployee(arg0: string, arg1: Employee): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, arg1);
            return result;
        }
    }
    async updateJobPosition(arg0: bigint, arg1: JobPosition): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobPosition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobPosition(arg0, arg1);
            return result;
        }
    }
    async updateTicketStatus(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTicketStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTicketStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async verifyAdminPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPassword(arg0);
            return result;
        }
    }

    async createAnnouncement(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Announcement> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0, arg1, arg2, arg3);
                return from_candid_Announcement(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0, arg1, arg2, arg3);
            return from_candid_Announcement(result);
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return result.map(from_candid_Announcement);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return result.map(from_candid_Announcement);
        }
    }
    async deleteAnnouncement(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async getAllLeaveRequests(): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeaveRequests();
                return result.map(from_candid_LeaveRequest);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeaveRequests();
            return result.map(from_candid_LeaveRequest);
        }
    }
    async getLeavesByEmployee(arg0: string): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeavesByEmployee(arg0);
                return result.map(from_candid_LeaveRequest);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeavesByEmployee(arg0);
            return result.map(from_candid_LeaveRequest);
        }
    }
    async getLeaveBalance(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveBalance(arg0);
            return result;
        }
    }
    async initOrRefreshLeaveBalance(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.initOrRefreshLeaveBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initOrRefreshLeaveBalance(arg0);
            return result;
        }
    }
    async applyLeave(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<LeaveRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.applyLeave(arg0, arg1, arg2, arg3, arg4);
                return from_candid_LeaveRequest(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyLeave(arg0, arg1, arg2, arg3, arg4);
            return from_candid_LeaveRequest(result);
        }
    }
    async approveLeaveRequest(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveLeaveRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveLeaveRequest(arg0, arg1);
            return result;
        }
    }

}
function from_candid_Announcement(value: import('./declarations/backend.did.d.ts').Announcement): Announcement {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        mediaFileId: value.mediaFileId,
        mediaType: value.mediaType,
        createdAt: value.createdAt,
    };
}
function from_candid_LeaveRequest(value: import('./declarations/backend.did.d.ts').LeaveRequest): LeaveRequest {
    return {
        id: value.id,
        employeeId: value.employeeId,
        reason: value.reason,
        startDate: value.startDate,
        endDate: value.endDate,
        numberOfDays: value.numberOfDays,
        status: value.status,
        requestedAt: value.requestedAt,
        approvedAt: value.approvedAt.length > 0 ? value.approvedAt[0] : undefined,
    };
}

function from_candid_Ticket_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Ticket {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TimesheetEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimesheetEntry): TimesheetEntry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TimesheetEntry]): TimesheetEntry | null {
    return value.length === 0 ? null : from_candid_TimesheetEntry_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobPosition]): JobPosition | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MailConfig]): MailConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: string;
    checkInTime: [] | [_Time];
    employeeId: string;
    checkOutTime: [] | [_Time];
}): {
    id: string;
    date: string;
    checkInTime?: Time;
    employeeId: string;
    checkOutTime?: Time;
} {
    return {
        id: value.id,
        date: value.date,
        checkInTime: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.checkInTime)),
        employeeId: value.employeeId,
        checkOutTime: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.checkOutTime))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    createdAt: _Time;
    description: string;
    ticketNumber: string;
    notes: string;
    category: string;
    raisedBy: string;
    resolvedAt: [] | [_Time];
}): {
    status: string;
    createdAt: Time;
    description: string;
    ticketNumber: string;
    notes: string;
    category: string;
    raisedBy: string;
    resolvedAt?: Time;
} {
    return {
        status: value.status,
        createdAt: value.createdAt,
        description: value.description,
        ticketNumber: value.ticketNumber,
        notes: value.notes,
        category: value.category,
        raisedBy: value.raisedBy,
        resolvedAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.resolvedAt))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ticket>): Array<Ticket> {
    return value.map((x)=>from_candid_Ticket_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimesheetEntry>): Array<TimesheetEntry> {
    return value.map((x)=>from_candid_TimesheetEntry_n10(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
